# -*- coding: utf-8 -*-
"""Task

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HkCbv2r_JcbQgT2Ums0bqbok7IeLZdE7
"""

print("Name\t\tRoll No.\tEmail ID \t\t\tPhone No\n"
      "Akshay\t\t07\t\takshaytribhuvan667@gmail.com\t9762060030\n"
      "pradumn\t\t11\t\tpc09@gmail.com\t\t\t9876543214\n"
      "Akshara\t\t21\t\takshara78@gmail.com\t\t9921222222\n"
      "Tribhuvan\t77\t\ttribhuvan77@gmail.com\t\t9960560096")

book = "Nature"
Author ="thinkpad"
Publication = "akshay"
PubDate = '15-03-2023'
print("My Book is",book, "Authored by" ,Author,"publication by ",Publication,"it's published at ",PubDate)

# Data Types
# int float string dict list set tuple boolean complex 
int1  = 12  # int
float1 = 13.7
str1 = "bame" # string
list1 = [12,"sadhg",12,.43]
set1  = {12,12,23,43,44,"AK","AK"} # set take only unique value 
tuple1 = (12,12,12,4) # it can take duplicate value

dict1 = {"Aurangabad":"PC","Name":"PC"}

list1

myInt = 77

myFloat = 89.9

list = ["pune", "Sambhajinagar", "Nagar","Mumbai", "Dhule"]

print(list)

dict77 = {"Dist" : "Sambhajinagar","Friend" : "Pc"}

print(dict77)

print("my friend is", dict77["Friend"],"he is from",dict77["Dist"])

nameOfCity = ["Pune","Sambhajinagar","Mumbai","Dhule","Nagar","Jalna","Nagpur","Shirdi","kopargaon"]

print("Currently I'm in", nameOfCity[2],"My home town is",nameOfCity[1],"In next month I will go",nameOfCity[3],"then I'm planing to go",nameOfCity[2])

list1[0:3]

list2 =[[1,2,3],["Ak",4,5],[5,6,7],[8,9,"Pc"]]

print(list2[0][2],"\t",list2[1][1],"\t",list2[2][0])
print(list2[3][2])

str2="Akshay"

print(str2[2:])

print(str2[4:-1])

print(str2[-3])

string = "Akshay Navnath Tribhuvan"

print(string.find(""))

NumberList = [1,2,3,4,5]

NewNumber = 10
NumberList.append(NewNumber)
print(NumberList)

task=[]
name = "Akshay"
list4 = [7,8,9]
set11 = {4,4,5}
task.append(name)
task.append(list4)
task.append(set11)
print(task)

int1  = 12 
float1 = 13.7
str1 = "bame" 
list1 = [12,"sadhg",12,.43]

myset = {int1,float1,str1}

myset.update(list1)

print(myset)

Name7 = "pc" #key 
roll_no = 45 #value 
dic7 = {Name7 : roll_no}
print(dic7)

Ak = ['A','B','C','D']
Pc = [1,2,3,4,5]

op= set(Ak)
set(Pc)

mydict= {}
mydict=dict(zip(Ak,Pc))
print(mydict)

NumberList = [4,45,34,1,3]

NumberFour=NumberList[3]
NumberOne=NumberList[0]

NumberList[3]=NumberOne
NumberList[0]=NumberFour

print(NumberList)

NumberList = [4,45,0,1,2,1,23,23,34,45,34,3,34,34,3,34,3,233,56,67,76,8,7,78,87,78,8778,78,7,23,23,34,45,34,3,34,34,3,34,3,233,56,67,76,8,7,78,87,78,8778,78,7]
NumberList.sort()
NumberList[-1]

NumberList = [4,45,0,1,2,1,23,23,34,45,34,3,34,34,3,34,3,233,56,67,76,8,7,78,87,78,8778,78,7,23,23,34,45,34,3,34,34,3,34,3,233,56,67,76,8,7,78,87,78,8778,78,7]
len(NumberList)
lenlist = len(NumberList) -1
NumberList[lenlist]

no = 2
add = no+3
print(add)

List1 = [23,12,43,5,7,1,3,4,5,5,6,7,7,8,88,4,3]
List1[1]=13
List1

List1[len(List1)-1]

lenght = len(List1)-1
List1[lenght]

# Create a list of 5 names then create another 4 variable which include some names add that variable in list and print last name of the list 
animal = ["dog","cat","tiger","horse","fish","cat","cat"]
bike = "Honda"
road = "JM"
area = "gokhalenagar"
plot = 403
animal.append(bike)
animal.append(road)
animal.append(area)
animal.append(plot)

animal.count("cat")

animal.index("horse")

animal.pop

animal = animal.reverse()
animal

Number = [1,773,34,45,8]
Number.reverse()
Number.sort(reverse= True)
Number

listx=[[1,2,3],[2,4,9,3,5],[3,7,8,9]]

listx[1]
len(listx[1])

set(listx[2])

dicx = {"Ak":"02","AA":"01","PC":"09","PP":"66"}
dicx["PC"]

len(dicx["PC"])

"""### Type casting """

Age = (input("Enter A number ="))
Age=float(Age)
print("type of this =",type(Age))

"""## Condition
* if else
* nested if

### if
"""

Age = 10
if Age != 10:
  print("Hello")
else:
  print("Bye")

# Create list of list  inside list should be greater than 5 value  take 3 list inside list check last list of list and print  "len of this list is greater than five" 
q = [[1,2,3,4,5,6],[4,2,1],['a',2,4]]
len(q[-1])
if len(q[-1]) > 5:
  print("len of this list is greater than five")
else:
  print("len is not greater than five")

number = int(input("Enter A number ="))
zz =(number)%2
if zz == 0:
  print("No is even")
else:
  print("No is odd")

number1 = int(input("Enter A number ="))
if (number1)%2 ==0:
   print("No is even")
else:
  print("No is odd")

"""### If Else if"""

Age = 17

if Age > 18:
  print("You are eligible to vote")
elif Age== 18:
  print("You are eligible to vote")
else: 
  print("You are not eligible")

"""Problem1: A company decided to give bonus of 5% to employee if his/her year of service is more than 5 years.
Ask user for their salary and year of service and print the net bonus amount.
"""

salary = int (input("enter your salary = "))
year = int (input("enter your year = "))
if year > 5:
  bonus = 5/100*(salary)
  print("net bonus amount = ",(bonus))
else:
  print("your not eligible for bonus")

"""Problem 2: Take values of length and breadth of a rectangle from user and check if it is square or not."""

lenght = int(input ("enter the lenght = "))
breadth = int(input ("enter the breadth = "))
if lenght == breadth:
  print("this is square ")
else:
  print("this is reactangle")

"""Problem 3: A school has following rules for grading system:
* a. Below 25 - F
* b. 25 to 45 - E
* c. 45 to 50 - D
* d. 50 to 60 - C
* e. 60 to 80 - B
* f. Above 80 - A

Ask user to enter marks and print the corresponding grade.
"""

marks = int(input("enter your marks = "))
if marks<25 :
  print("Grade F")
elif marks<= 45:
  print("Grade E")
elif marks<=50:
  print("Grade D")
elif marks<=60:
  print("Grade C")
elif marks<=80:
  print("Grade B")
elif marks>80:
  print("Grade A")
else:
  print("plaese check your marks")

